package ch.bfh.bti7081.s2018.yellow.health.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainView extends AbsoluteLayout {
	protected Label lbl_Name;
	protected Label lbl_FirstName;
	protected TextField txt_Name;
	protected TextField txt_FirstName;
	protected Label lbl_Relative;
	protected TextField txt_Relative;
	protected Button but_Search;

	public MainView() {
		Design.read(this);
	}
}
