package ch.bfh.bti7081.s2018.yellow.health.ui.layouts;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class LoginLayout extends AbsoluteLayout {
	private Label lbl_Username;
	private TextField txt_Username;
	private Label lbl_Password;
	private PasswordField txt_Password;
	private Button but_login;
	private Button but_register1;
	private Label lbl_Notification;

	public LoginLayout() {
		Design.read(this);
	}

	public Label getLbl_Username() {
		return lbl_Username;
	}

	public TextField getTxt_Username() {
		return txt_Username;
	}

	public Label getLbl_Password() {
		return lbl_Password;
	}

	public PasswordField getTxt_Password() {
		return txt_Password;
	}

	public Button getBut_login() {
		return but_login;
	}

	public Button getBut_register1() {
		return but_register1;
	}

	public Label getLbl_Notification() {
		return lbl_Notification;
	}
}
